name: Release

on:
  workflow_dispatch:
    inputs:
      acknowledge:
        description: 'I understand that this action will publish everything on dev to the latest tag'
        required: true
        type: boolean

jobs:
  release:
    if: ${{ inputs.acknowledge }}
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'master'
          token: ${{ secrets.CI_PERSONAL_ACCESS_TOKEN }}

      - name: Merge next into master
        run: |
          git merge --ff-only origin/next
          git push
